# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c4012b88a53bb9128df4b54879fe3ccb890767cbc6df883292ac88285f7d7f2b25a8bf2e537122730d2efc5503a07512da4e123b5ac9d7574bf8374306aaa8e

test:
  secret_key_base: c6c2a2832cf7f28926100c2f5be58de2c9f7bd36f66c1af11cc8981fea8f7c1944643fb837501b224618d42d928a42cb3bd664126dbd82429b852349acf117fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
